"""fix tables

Revision ID: 0fa15cb0692f
Revises: 3b109881ade5
Create Date: 2025-03-02 20:11:03.512365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa15cb0692f'
down_revision: Union[str, None] = '3b109881ade5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('login', sa.String(length=250), nullable=False))
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'login')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
