"""rename field in receipts

Revision ID: 26bcee7dc375
Revises: dde469c6a24c
Create Date: 2025-03-03 21:40:32.404792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bcee7dc375'
down_revision: Union[str, None] = 'dde469c6a24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('text_file_path', sa.String(length=250), nullable=True))
    op.add_column('receipts', sa.Column('qr_file_path', sa.String(length=250), nullable=True))
    op.drop_column('receipts', 'qr_code_url')
    op.drop_column('receipts', 'text_receipt_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('text_receipt_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('qr_code_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('receipts', 'qr_file_path')
    op.drop_column('receipts', 'text_file_path')
    # ### end Alembic commands ###
