"""del fields

Revision ID: cd0f6a1b56cf
Revises: 26bcee7dc375
Create Date: 2025-03-03 22:49:55.573326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0f6a1b56cf'
down_revision: Union[str, None] = '26bcee7dc375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'text_file_path')
    op.drop_column('receipts', 'qr_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('qr_file_path', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('text_file_path', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
