"""added urls

Revision ID: dde469c6a24c
Revises: d76871bde060
Create Date: 2025-03-03 13:04:40.952796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde469c6a24c'
down_revision: Union[str, None] = 'd76871bde060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('text_receipt_url', sa.String(length=250), nullable=True))
    op.add_column('receipts', sa.Column('qr_code_url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'qr_code_url')
    op.drop_column('receipts', 'text_receipt_url')
    # ### end Alembic commands ###
